const keywordIcons = {
  shopping: "🛒",
  football: "⚽",
  learning: "📚",
  music: "🎵",
  travel: "✈️",
  food: "🍔",
  book: "📖",
  movie: "🎬",
  game: "🎮",
  phone: "📱",
  laptop: "💻",
  money: "💵",
  love: "❤️",
  cat: "🐱",
  dog: "🐶",
  weather: "⛅",
  car: "🚗",
  bike: "🚲",
  camera: "📷",
  work: "💼",
  study: "📝",
  gym: "🏋️",
  relax: "🛋️",
  sleep: "😴",
  idea: "💡",
  art: "🎨",
  coffee: "☕",
  tea: "🍵",
  plant: "🪴",
  gift: "🎁",
  birthday: "🎂",
  time: "⏰",
};
export default keywordIcons;
